title: PROPTIT
description: PROPTIT BLOG
author: PROPTIT
github: "https://github.com/proptitclub"
about: PROPTIT-CLUB
enableTags: true
tagarray: []
collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/clubproptit"

    - icon: fa-github
      link: "https://github.com/proptitclub"

urls:
    - text: About Me
      url: /about/
    - text: Project
      url: /projects/
    - text : Category
      url : /category/AI
url: "https://proptitclub.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
